version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "5.0.0"
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
    image: simple-todo:v5
    # container_name: simple-todo-web   # optional; remove to avoid name collisions
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    user: "10001:10001"
    volumes:
      - app_data:/app/data
    networks:
      - todo_network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:5000/healthz').status==200 else 1)"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3

  db:
    image: postgres:16-alpine
    # container_name: simple-todo-db     # optional
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

volumes:
  postgres_data:
    driver: local
  app_data:
    driver: local

networks:
  todo_network:
    driver: bridge