global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'simple-todo-monitor'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'simple-todo-web'
    static_configs:
      - targets: ['web:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: false
    params:
      format: ['prometheus']

  # Optional: scrape worker metrics if exposed
  - job_name: 'simple-todo-worker'
    static_configs:
      - targets: ['worker:8000']  # If you decide to expose worker metrics
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: false
    params:
      format: ['prometheus']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s
